FROM ghcr.io/dav-xzac/mlops-base:latest AS builder

# installa solo librerie dell’app
RUN pip install --no-cache-dir \
        fastapi \
        pydantic \
        uvicorn[standard] \
        gradio

# Stage runtime pulito
FROM python:3.12-slim

ENV PYTHONUNBUFFERED=1
WORKDIR /app

# Copia solo le librerie dal builder stage
COPY --from=builder /usr/local /usr/local

# Copia codice dell’app
COPY . .

CMD ["python", "app_sentiment.py"]

