name: Api post fetching

on:
    schedule:
        - cron: '12 7 * * *'
    workflow_dispatch:

jobs:
    fetch_data_from_api:
        runs-on: ubuntu-latest
        steps:
            - name: api_call
              uses: actions/checkout@v4
            - uses: actions/setup-python@v4
              with: { python-version: '3.12'}
            - run: pip install requests fast_langdetect
            - run: python3 -m data_collection/data/mastodon.py


