name: Deploy app to HuggingFace Space

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - "app/**"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push app/ to HuggingFace Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config --global user.email "ci@github.com"
          git config --global user.name "GitHub Actions"
          cd app
          git init
          git add .
          git commit -m "deploy: $(date +%Y-%m-%d)"
          git push --force https://divde:$HF_TOKEN@huggingface.co/spaces/divde/sentiment_proj_5 HEAD:main
