name: grafana

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - "app/**"
      - "monitoring/**"

jobs:
  deploy_monitoring:
    runs-on: ubuntu-latest
    env:
      GRAFANA_TOKEN: ${{ secrets.GRAFANA_TOKEN}}
      GRAFANA_INSTANCE: ${{ vars.GRAFANA_INSTANCE}}
      SPACE_URL: ${{ vars.SPACE_URL}}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - run: pip install requests
    
      - name: Create infinity datasource with aligned uid and push dashboard
        run: python scripts/deploy_grafana.py



