name: Automated Retrain on Kaggle

on:
    workflow_dispatch:
    schedule:
        - cron: '33 7 * * *'

jobs:
    check_drift:
        runs-on: ubuntu-latest
        outputs:
            drift: ${{ steps.check.outputs.drift}}
        env:
            SPACE_URL: ${{ vars.SPACE_URL}}
        steps:
            - id: check
              run: |
                stats=$(curl -s "$SPACE_URL/weekly_stats")
                total=$(echo "$stats" | jq '.total_predictions_7d')
                avg=$(echo "$stats" | jq '.avg_confidence_7d')
                echo "Week Total Predictions: $total | Avg confidence: $avg"

                if ((total < 100 )); then
                    echo "Insufficient data collected, skip retraining"
                    echo "drift=false" >> "$GITHUB_OUTPUT"
                elif (( $(echo "$avg < 0.80" | bc -l) )); then
                    echo "drift=true" >> "$GITHUB_OUTPUT"
                else
                    echo "drift=false" >> "$GITHUB_OUTPUT"
                fi



    update_secrets:
        needs: check_drift
        if: needs.check_drift.outputs.drift == 'true' || github.event_name != 'schedule'
        runs-on: ubuntu-latest
        env:
            KAGGLE_API_TOKEN: ${{ secrets.KAGGLE_TOKEN }}
            KAGGLE_USERNAME: ${{ vars.KAGGLE_USERNAME }}
            HF_TOKEN: ${{ secrets.HF_TOKEN}}
            HF_USER: ${{ vars.HF_USER}}
            SPACE_URL: ${{ vars.SPACE_URL }}
            MODEL_REPO: ${{ vars.MODEL_REPO}}
            METRICS_REPO: ${{ vars.METRICS_REPO}}
            SYNTH_DATA_REPO: ${{ vars.SYNTH_DATA_REPO}}
            SPACE_NAME: ${{ vars.SPACE_NAME}}
            COMPANY: ${{ vars.COMPANY}}
            COMPANY_DESC: ${{ vars.COMPANY_DESC}}
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-python@v4
              with: { python-version: '3.12' }
            - run : pip install kaggle --upgrade
            - run: bash scripts/update_kaggle_secrets.sh


    retrain:
        needs: [check_drift, update_secrets]
        if: needs.check_drift.outputs.drift == 'true' || github.event_name != 'schedule'
        runs-on: ubuntu-latest
        env:
            KAGGLE_API_TOKEN: ${{ secrets.KAGGLE_TOKEN }}
            KAGGLE_USERNAME: ${{ vars.KAGGLE_USERNAME }}
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
            - uses: actions/setup-python@v4
              with: { python-version: '3.12' }
            - run: pip install kaggle --upgrade
            - run: |
                jq --arg id "$KAGGLE_USERNAME/sentiment-retraining" --arg secrets "$KAGGLE_USERNAME/secrets" \
                    '.id = $id | .dataset_sources = [$secrets]' \
                    model/kernel-metadata_template.json > model/kernel-metadata.json
            - run: kaggle kernels push -p ./model/ --accelerator NvidiaTeslaT4


