name: Automated Retrain on Kaggle

on:
    workflow_dispatch:
    schedule:
        - cron: '33 7 * * *'

jobs:
    check_drift:
        runs-on: ubuntu-latest
        outputs:
            drift: ${{ steps.check.outputs.drift}}
        env:
            SPACE_URL: ${{ vars.SPACE_URL}}
        steps:
            - id: check
              run: |
                stats=$(curl -s "$SPACE_URL/weekly_stats")
                total=(echo "$stats" | jq '.total_predictions_7d')
                avg=$(echo "$stats" | jq '.acg_confidence_7d')
                echo "Week Total Predictions: $total | Avg confidence: $avg"

                if ((total < 100 )); then
                    echo "Insufficent data collected, skip retraining"
                    echo "drift=false" >> "$GITHUB_OUTPUT"
                elif (( $(echo "$avg < 0.80" | bc -1) )); then
                    echo "drift=true" >> "$GITHUB_OUTPUT"
                else
                    echo "drift=false" >> "$GITHUB_OUTPUT"
                fi



    update_secrets:
        needs: check_drift
        if: needs.check_drift.outputs.drift == 'true' || github.event_name != 'schedule'
        runs-on: ubuntu-latest
        env:
            KAGGLE_API_TOKEN: ${{ secrets.KAGGLE_TOKEN }}
            KAGGLE_USERNAME: ${{ vars.KAGGLE_USERNAME }}
            HF_TOKEN: ${{ secrets.HF_TOKEN}}
            HF_USER: ${{ vars.HF_USER}}
            SPACE_URL: ${{ vars.SPACE_URL }}
            MODEL_REPO: ${{ vars.MODEL_REPO}}
            METRICS_REPO: ${{ vars.METRICS_REPO}}
            SYNTH_DATA_REPO: ${{ vars.SYNTH_DATA_REPO}}
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-python@v4
              with: { python-version: '3.12' }
            - run : pip install kaggle --upgrade
            - run: |
                mkdir -p /tmp/kaggle-secrets

                jq --arg id "$KAGGLE_USERNAME/secrets" \
                    '.id = $id' \
                    secrets/dataset-metadata_template.json > /tmp/kaggle-secrets/dataset-metadata.json
                

                jq --arg token "$HF_TOKEN" --arg user "$HF_USER" \
                   --arg repo "$MODEL_REPO" --arg metrics "$METRICS_REPO" \
                   --arg synth "$SYNTH_DATA_REPO" --arg space "$SPACE_URL" \
                   '.HF_TOKEN = $token | .HF_USER = $user | .MODEL_REPO = $repo | .METRICS_REPO = $metrics | .SYNTH_DATA_REPO = $synth | .SPACE_URL= $space' \
                   secrets/secrets_template.json > /tmp/kaggle-secrets/secrets.json

                if kaggle datasets metadata -d $KAGGLE_USERNAME/secrets &>/dev/null; then
                    kaggle datasets version -p /tmp/kaggle-secrets -m "update"
                else
                    kaggle datasets create -p /tmp/kaggle-secrets
                fi

    retrain:
        needs: [check_drift, update_secrets]
        if: needs.check_drift.outputs.drift == 'true' || github.event_name != 'schedule'
        runs-on: ubuntu-latest
        env:
            KAGGLE_API_TOKEN: ${{ secrets.KAGGLE_TOKEN }}
            KAGGLE_USERNAME: ${{ vars.KAGGLE_USERNAME }}
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
            - uses: actions/setup-python@v4
              with: { python-version: '3.12' }
            - run: pip install kaggle --upgrade
            - run: |
                jq --arg id "$KAGGLE_USERNAME/sentiment-retraining" --arg secrets "$KAGGLE_USERNAME/secrets" \
                    '.id = $id | .dataset_sources = [$secrets]' \
                    model/kernel-metadata_template.json > model/kernel-metadata.json
            - run: kaggle kernels push -p ./model/ --accelerator NvidiaTeslaT4


