name: Set variables and secret on HF

on:
  workflow_dispatch:

jobs:
  bootstrap:
    runs-on: ubuntu-latest
    env:
      HF_TOKEN: ${{ secrets.HF_TOKEN }}
      HF_USER: ${{ vars.HF_USER }}
      SPACE_NAME: ${{ vars.SPACE_NAME }}
      MODEL_REPO: ${{ vars.MODEL_REPO }}
      GRAFANA_URL: ${{ vars.GRAFANA_URL }}
      KAGGLE_USERNAME: ${{ vars.KAGGLE_USERNAME }}
      COMPANY: ${{ vars.COMPANY }}
      SYNTH_DATA_REPO: ${{ vars.SYNTH_DATA_REPO }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with: { python-version: '3.12' }
      - run: pip install huggingface_hub
      - run: python scripts/set_variables_and_secrets.py
